package com.tair.dataware.db;

// Generated 2011-7-27 17:45:15 by Hibernate Tools 3.4.0.CR1

/**
 * Groupinfo generated by hbm2java
 */
public class Groupinfo implements java.io.Serializable {

	private Integer gid;
	private String domainA;
	private String ipa;
	private int portA;
	private String domainB;
	private String ipb;
	private Integer portB;
	private String groupName;
	private String description;
	private String tairRelease;
	private String scene;
	private String monitorUrlbase;
	private String wikiUrl;

	public Groupinfo() {
	}

	public Groupinfo(String domainA, int portA) {
		this.domainA = domainA;
		this.portA = portA;
	}

	public Groupinfo(String domainA, String ipa, int portA, String domainB,
			String ipb, Integer portB, String groupName, String description,
			String tairRelease, String scene, String monitorUrlbase,
			String wikiUrl) {
		this.domainA = domainA;
		this.ipa = ipa;
		this.portA = portA;
		this.domainB = domainB;
		this.ipb = ipb;
		this.portB = portB;
		this.groupName = groupName;
		this.description = description;
		this.tairRelease = tairRelease;
		this.scene = scene;
		this.monitorUrlbase = monitorUrlbase;
		this.wikiUrl = wikiUrl;
	}

	public Integer getGid() {
		return this.gid;
	}

	public void setGid(Integer gid) {
		this.gid = gid;
	}

	public String getDomainA() {
		return this.domainA;
	}

	public void setDomainA(String domainA) {
		this.domainA = domainA;
	}

	public String getIpa() {
		return this.ipa;
	}

	public void setIpa(String ipa) {
		this.ipa = ipa;
	}

	public int getPortA() {
		return this.portA;
	}

	public void setPortA(int portA) {
		this.portA = portA;
	}

	public String getDomainB() {
		return this.domainB;
	}

	public void setDomainB(String domainB) {
		this.domainB = domainB;
	}

	public String getIpb() {
		return this.ipb;
	}

	public void setIpb(String ipb) {
		this.ipb = ipb;
	}

	public Integer getPortB() {
		return this.portB;
	}

	public void setPortB(Integer portB) {
		this.portB = portB;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getTairRelease() {
		return this.tairRelease;
	}

	public void setTairRelease(String tairRelease) {
		this.tairRelease = tairRelease;
	}

	public String getScene() {
		return this.scene;
	}

	public void setScene(String scene) {
		this.scene = scene;
	}

	public String getMonitorUrlbase() {
		return this.monitorUrlbase;
	}

	public void setMonitorUrlbase(String monitorUrlbase) {
		this.monitorUrlbase = monitorUrlbase;
	}

	public String getWikiUrl() {
		return this.wikiUrl;
	}

	public void setWikiUrl(String wikiUrl) {
		this.wikiUrl = wikiUrl;
	}

}
