package com.tair.dataware.db;

// Generated 2011-7-27 17:45:15 by Hibernate Tools 3.4.0.CR1

/**
 * Maillist generated by hbm2java
 */
public class Maillist implements java.io.Serializable {

	private Integer id;
	private String role;
	private String mail;

	public Maillist() {
	}

	public Maillist(String role, String mail) {
		this.role = role;
		this.mail = mail;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

}
